# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.srcs/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/ASSEMBLY_TEMPLATE_smartconnect_1_1.xci
# IP: The module: 'ASSEMBLY_TEMPLATE_smartconnect_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/bd_5234.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_0/bd_5234_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_1/bd_5234_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_2/bd_5234_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_3/bd_5234_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_4/bd_5234_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_5/bd_5234_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_6/bd_5234_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_7/bd_5234_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_8/bd_5234_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_9/bd_5234_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_10/bd_5234_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_1/bd_5234_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_1/bd_5234_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_5/bd_5234_s00a2s_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_6/bd_5234_sawn_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_6/bd_5234_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_7/bd_5234_swn_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_7/bd_5234_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_8/bd_5234_sbn_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_8/bd_5234_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_9/bd_5234_m00s2a_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASSEMBLY_TEMPLATE_smartconnect_1_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASSEMBLY_TEMPLATE_smartconnect_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.srcs/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/ASSEMBLY_TEMPLATE_smartconnect_1_1.xci
# IP: The module: 'ASSEMBLY_TEMPLATE_smartconnect_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/bd_5234.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_0/bd_5234_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_1/bd_5234_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_2/bd_5234_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_3/bd_5234_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_4/bd_5234_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_5/bd_5234_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_6/bd_5234_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_7/bd_5234_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_8/bd_5234_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_9/bd_5234_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_10/bd_5234_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_1/bd_5234_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_1/bd_5234_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_5/bd_5234_s00a2s_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_6/bd_5234_sawn_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_6/bd_5234_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_7/bd_5234_swn_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_7/bd_5234_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_8/bd_5234_sbn_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_8/bd_5234_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/bd_0/ip/ip_9/bd_5234_m00s2a_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASSEMBLY_TEMPLATE_smartconnect_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASSEMBLY_TEMPLATE_smartconnect_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
