# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.srcs/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_axi_dma_0_0/ASSEMBLY_TEMPLATE_axi_dma_0_0.xci
# IP: The module: 'ASSEMBLY_TEMPLATE_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_axi_dma_0_0/ASSEMBLY_TEMPLATE_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASSEMBLY_TEMPLATE_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_axi_dma_0_0/ASSEMBLY_TEMPLATE_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASSEMBLY_TEMPLATE_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_axi_dma_0_0/ASSEMBLY_TEMPLATE_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASSEMBLY_TEMPLATE_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.srcs/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_axi_dma_0_0/ASSEMBLY_TEMPLATE_axi_dma_0_0.xci
# IP: The module: 'ASSEMBLY_TEMPLATE_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_axi_dma_0_0/ASSEMBLY_TEMPLATE_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASSEMBLY_TEMPLATE_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_axi_dma_0_0/ASSEMBLY_TEMPLATE_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASSEMBLY_TEMPLATE_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_axi_dma_0_0/ASSEMBLY_TEMPLATE_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASSEMBLY_TEMPLATE_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
