# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.srcs/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/ASSEMBLY_TEMPLATE_smartconnect_0_0.xci
# IP: The module: 'ASSEMBLY_TEMPLATE_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/bd_52a4.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_0/bd_52a4_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_1/bd_52a4_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_2/bd_52a4_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_3/bd_52a4_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_4/bd_52a4_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_5/bd_52a4_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_6/bd_52a4_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_7/bd_52a4_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_8/bd_52a4_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_9/bd_52a4_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_1/bd_52a4_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_1/bd_52a4_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_5/bd_52a4_s00a2s_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_6/bd_52a4_sarn_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_6/bd_52a4_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_7/bd_52a4_srn_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_7/bd_52a4_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_8/bd_52a4_m00s2a_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASSEMBLY_TEMPLATE_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASSEMBLY_TEMPLATE_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.srcs/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/ASSEMBLY_TEMPLATE_smartconnect_0_0.xci
# IP: The module: 'ASSEMBLY_TEMPLATE_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/bd_52a4.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_0/bd_52a4_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_1/bd_52a4_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_2/bd_52a4_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_3/bd_52a4_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_4/bd_52a4_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_5/bd_52a4_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_6/bd_52a4_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_7/bd_52a4_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_8/bd_52a4_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_9/bd_52a4_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_1/bd_52a4_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_1/bd_52a4_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_5/bd_52a4_s00a2s_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_6/bd_52a4_sarn_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_6/bd_52a4_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_7/bd_52a4_srn_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_7/bd_52a4_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/bd_0/ip/ip_8/bd_52a4_m00s2a_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASSEMBLY_TEMPLATE_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'ASSEMBLY_TEMPLATE_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
