# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ASSEMBLY_TEMPLATE/ASSEMBLY_TEMPLATE.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_TEMPLATE || ORIG_REF_NAME==ASSEMBLY_TEMPLATE} -quiet] -quiet

# IP: bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_zynq_ultra_ps_e_0_0/ASSEMBLY_TEMPLATE_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_TEMPLATE_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ASSEMBLY_TEMPLATE_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_xbar_0/ASSEMBLY_TEMPLATE_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_TEMPLATE_xbar_0 || ORIG_REF_NAME==ASSEMBLY_TEMPLATE_xbar_0} -quiet] -quiet

# IP: bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_axi_interconnect_0_0/ASSEMBLY_TEMPLATE_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_TEMPLATE_axi_interconnect_0_0 || ORIG_REF_NAME==ASSEMBLY_TEMPLATE_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_0_0/ASSEMBLY_TEMPLATE_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_TEMPLATE_smartconnect_0_0 || ORIG_REF_NAME==ASSEMBLY_TEMPLATE_smartconnect_0_0} -quiet] -quiet

# IP: bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_proc_sys_reset_0_0/ASSEMBLY_TEMPLATE_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_TEMPLATE_proc_sys_reset_0_0 || ORIG_REF_NAME==ASSEMBLY_TEMPLATE_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_axis_ann_0_0/ASSEMBLY_TEMPLATE_axis_ann_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_TEMPLATE_axis_ann_0_0 || ORIG_REF_NAME==ASSEMBLY_TEMPLATE_axis_ann_0_0} -quiet] -quiet

# IP: bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_axi_dma_0_0/ASSEMBLY_TEMPLATE_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_TEMPLATE_axi_dma_0_0 || ORIG_REF_NAME==ASSEMBLY_TEMPLATE_axi_dma_0_0} -quiet] -quiet

# IP: bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_smartconnect_1_1/ASSEMBLY_TEMPLATE_smartconnect_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_TEMPLATE_smartconnect_1_1 || ORIG_REF_NAME==ASSEMBLY_TEMPLATE_smartconnect_1_1} -quiet] -quiet

# IP: bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_auto_ds_0/ASSEMBLY_TEMPLATE_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_TEMPLATE_auto_ds_0 || ORIG_REF_NAME==ASSEMBLY_TEMPLATE_auto_ds_0} -quiet] -quiet

# IP: bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_auto_pc_0/ASSEMBLY_TEMPLATE_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_TEMPLATE_auto_pc_0 || ORIG_REF_NAME==ASSEMBLY_TEMPLATE_auto_pc_0} -quiet] -quiet

# IP: bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_auto_ds_1/ASSEMBLY_TEMPLATE_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_TEMPLATE_auto_ds_1 || ORIG_REF_NAME==ASSEMBLY_TEMPLATE_auto_ds_1} -quiet] -quiet

# IP: bd/ASSEMBLY_TEMPLATE/ip/ASSEMBLY_TEMPLATE_auto_pc_1/ASSEMBLY_TEMPLATE_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ASSEMBLY_TEMPLATE_auto_pc_1 || ORIG_REF_NAME==ASSEMBLY_TEMPLATE_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/ASSEMBLY_TEMPLATE_VER/ASSEMBLY_TEMPLATE_VER.gen/sources_1/bd/ASSEMBLY_TEMPLATE/ASSEMBLY_TEMPLATE_ooc.xdc
